# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-12 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_project_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='tickets_tags', to='tickets.Tag'),
        ),
    ]
